### ISSUE TITLE
Output to oedb

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.powerflow#36]
In order to save the powerflow results in the oedb an sqla interface has to be created. 
A corresponding structure on the oedb has to be developed.

@gplssm is interested in this topic as well.

@mariusves Have you created a branch already? Is there a first draft for the structure in the oedb already existing?

**Comment by mariusves** [comment]
The branch is created.
Here are the ToDos:
- [x]  Add 'create table' parts in data processing sql snippet and run it in oedb
- [x]  Add respective classes in ego.io file
- [x]  Add actual exporting function to tools/io.py

**Comment by mariusves** [comment]
The existing exporter is now expended to contain all of the pypsa outputs. The branches needed are:
https://github.com/openego/ego.io/tree/features/add-pf-result-tables
https://github.com/openego/ego.powerflow/tree/features/add-export2db
https://github.com/openego/data_processing/tree/features/add-pf-result2db

The result tables are so far only created for HV. There is a result meta table containing the following data
- result_id
- scn_name
- calc_date
- calc_type
- commentary

@gplssm As you can see, I've changed the existing export function a little bit.
Since the original function was created quite a while back: is it still being used? If you want, I could easily adapt the hv structure for the mv level as well.

**Comment by gplssm** [comment]
Thanks for keeping me up-to-date!

Currently, we're not using that much of ego.powerflow, because we bypass the OEDB when running power flow calculations in Dingo. The same for [eDisGo](https://github.com/openego/edisgo) (the tool for actual MV/LV grid analyses we're currently developing) will bypass the OEDB for power flow, but we are interested to export grid topologies in general. For example, we would like to export grid topologies resulting from Dingo. Therefore, we'll be inspired by your work! 
Regarding changes in this file, feel free and do it :+1:

**Comment by mariusves** [comment]
Feature is currently implemented. Improvements will be handled in eTraGo.
